const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tabs': 'Tabs',
  '/forms': 'Forms',
  '/forms/basic-forms': 'Basic Forms',
  '/forms/advanced-forms': 'Advanced Forms',
  '/editors': 'Editors',
  '/editors/text-editors': 'Text Editors',
  '/editors/code-editors': 'Code Editors',
  '/plugins': 'Plugins',
  '/plugins/calendar': 'Calendar',
  '/plugins/notifications': 'Notifications',
  '/plugins/spinners': 'Spinners',
  '/google-maps': 'Google Maps',
  '/staff-management': 'Quản lí Nhân Viên',
  '/customer-management': 'Quản lí Khách Hàng',
  '/warehouse-management': 'Quản lí nhập xuất kho hàng',
  '/warehouse-management/enter': 'Nhập kho',
  '/warehouse-management/export': 'Xuất kho',
  '/bill-management/invoice': 'Lập hóa đơn',
  '/bill-management/income-spend': 'Quản lí thu/chi',
};
export default routes;
